Updated the module to also be compatible with latest testing suite mo…
mediact/coding-standard pull request #14
Opened 2021-03-10 15:27 UTC by leonhelmus

…dule & dropped support php 5.x.

- PHP 5.x support.
- Phpunit is required by mediact testing suite and is not a requirement for this module.

- PhpStorm 2020 has changed there config folder to a different path.

- Refactored code to fix testing suite issues.

- [Dev Docker](https://github.com/mediact/docker-compose-development-manager)
- Compatibility with latest testing suite module.

2021-03-11 08:06 UTC, ksangers requested changes

2021-03-11 08:06 UTC, ksangers commented on .env.dev
> +CLOUDSDK_PYTHON=/usr/bin/python
Is not used, please remove or use it.

2021-03-16 08:16 UTC, leonhelmus commented
Ik heb ook de scrutenizer gefixed :)

2021-03-16 09:27 UTC, ksangers approved these changes

2021-03-16 09:28 UTC, merged